version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - '@abmccull'
    labels:
      - 'dependencies'
      - 'automated'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    pull-request-branch-name:
      separator: '-'
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      # Keep major updates separate for careful review
      major:
        patterns:
          - '*'
        update-types:
          - 'major'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@abmccull'
    labels:
      - 'github-actions'
      - 'automated'
    commit-message:
      prefix: 'ci'
      include: 'scope'
